### ISSUE TITLE
strong Vpn的问题

### ISSUE THREAD

**Issue by hylls** [vpnforchina/vpnforchina.github.io#13]
用的是国内特供客户端 windows系统 

连接节点以后出现这个问题

an error occured while trying to connect

TLS key negotiation failed to occur within 15 seconds (check your network connectivity)

**Comment by vpnforchina** [comment]
抱歉，回复晚了。
建议换个节点，使用精简客户端OpenVPN（TCP）协议进行连接。
我这边连接状态一直都正常。
