### ISSUE TITLE
strongVPN大部分服务器无法连接

### ISSUE THREAD

**Issue by haoyiqiang** [vpnforchina/vpnforchina.github.io#14]
首先提供的大多数都是美国节点，只有很少部分新加坡，日本节点。总共服务器数量大概在二三十个，其中大部分还是无法连接上的。能连上的网速也慢的可怜。中国用户只用通过V1客户端才能连上，下载官网V2客户端就不要想连上了。strongVPN是个深坑，请谨慎购买。

**Comment by vpnforchina** [comment]
我这边用着还行，不好用30天内可以退，直接申请就行了，到帐很快。

**Comment by wooboo-sh** [comment]
经常连不上，这个VPN真不咋的
