### ISSUE TITLE
登录出错

### ISSUE THREAD

**Issue by Kbaseczy** [vpnforchina/vpnforchina.github.io#8]
提示以下内容：An error occurred while sending the request.

**Comment by vpnforchina** [comment]
什么系统？什么软件？如果是StrongVPN的话，建议使用精简版V1 App客户端，适合在国内使用，可以找客服获取，文章中已经说明了。

**Comment by jdxl11** [comment]
找不到customer area啊.........，想要个ticket找不到地方

**Comment by jdxl11** [comment]
我写的是 no available accounts

**Comment by vpnforchina** [comment]
> 
> 
> 找不到customer area啊.........，想要个ticket找不到地方

登录进去用户后台就是Customer Area，点击Support Tickets。
